"""
混合RAG系统配置文件
包含所有系统配置参数和常量定义
"""

import os
import logging

# 日志配置
LOG_LEVEL = logging.INFO
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
LOG_FILE = 'hybrid_rag.log'

# DashScope API配置
DASHSCOPE_API_KEY = os.getenv("DASHSCOPE_API_KEY", "")

# 系统默认配置
DEFAULT_CONFIDENCE_THRESHOLD = 0.3
MAX_RETRIEVAL_RESULTS = 10
ERROR_PROPAGATION_THRESHOLD = 0.3

# 嵌入模型配置
EMBEDDING_MODEL_NAME = "text-embedding-v3"
FALLBACK_EMBEDDING_MODEL = 'all-MiniLM-L6-v2'
EMBEDDING_DIMENSION = 1536

# Neo4j配置
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "password"

# LLM配置
LLM_MODEL_NAME = "qwen-turbo"
LLM_JSON_MODEL = "qwen-turbo"
LLM_TEXT_MODEL = "qwen-turbo"

# 检索配置
RETRIEVAL_TOP_K = 5
RETRIEVAL_VECTOR_WEIGHT = 0.5
RETRIEVAL_KEYWORD_WEIGHT = 0.3
RETRIEVAL_GRAPH_WEIGHT = 0.2

# 关键词配置
KEYWORD_THRESHOLD = 0.1
KEYWORD_MAX_KEYWORDS = 10
KEYWORD_MIN_KEYWORD_LENGTH = 2

# 文档配置
DOCUMENT_MIN_LENGTH = 10
DOCUMENT_MAX_LENGTH = 10000
DOCUMENT_ENCODING = 'utf-8'

# 图数据库配置
GRAPH_MAX_DEPTH = 3
GRAPH_MAX_HOPS = 3
GRAPH_MIN_CONFIDENCE = 0.2
GRAPH_MAX_RELATIONSHIPS = 50

# 答案生成配置
ANSWER_MAX_TOKENS = 1000
ANSWER_TEMPERATURE = 0.7
ANSWER_TOP_P = 0.9
ANSWER_MAX_CONTEXT_DOCS = 5
ANSWER_MAX_GRAPH_RELATIONS = 10